name: rattle
version: 0.0.1
summary: Rattle Next Generation Data Science App
description: Rattle is the data scientists toolkit.

confinement: strict
base: core18
grade: stable

slots:
  dbus-rattle: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.togaware.rattle # adjust accordingly to your app name and
    
apps:
  rattle:
    command: rattle
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-rattle
parts:
  rattle:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

plugs:
  r-executable:
    interface: system-files
    read:
      - /usr/bin/R
